### ISSUE TITLE
Quantile plots fail when horizon is 1 

### ISSUE THREAD

**Issue by antoinecarme** [antoinecarme/pyaf#168]
Quantile plots fail when horizon is 1 on ozone dataset (regression introduced with #158)

```
Traceback (most recent call last):
  File "/home/dev/python/packages/timeseries/pyaf/tests/func/test_ozone_horizon_one.py", line 32, in <module>
    lEngine.standardPlots("outputs/my_ozone_horizon_one");
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/ForecastEngine.py", line 48, in standardPlots
    self.mSignalDecomposition.standardPlots(name, format);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition.py", line 763, in standardPlots
    self.mBestModels[lSignal].standardPlots(lName, format);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/TimeSeriesModel.py", line 379, in standardPlots
    tsplot.quantiles_plot(lOutput,
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/Plots.py", line 176, in quantiles_plot
    _, bins1, patches = axs[h].hist(q_values, bins = q_values, weights=[1]*len(lQuantileNames), density = True)
TypeError: 'AxesSubplot' object is not subscriptable

```

**Comment by antoinecarme** [comment]
Closing
