### ISSUE TITLE
Failure in an artificial test

### ISSUE THREAD

**Issue by antoinecarme** [antoinecarme/pyaf#34]
After updating #6 , The following test fails : 

python3  tests/artificial/transf_log/trend_constant/cycle_12/ar_12/test_artificial_1024_log_constant_12_12_100.py

**Comment by antoinecarme** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/artificial/transf_log/trend_constant/cycle_12/ar_12/test_artificial_1024_log_constant_12_12_100.py", line 9, in <module>
    art.process_dataset(dataset);
  File "/home/antoine/dev/python/packages/pyaf/tests/artificial/process_artificial_dataset.py", line 19, in process_dataset
    process_dataset_with_noise(idataset, sig);
  File "/home/antoine/dev/python/packages/pyaf/tests/artificial/process_artificial_dataset.py", line 47, in process_dataset_with_noise
    lEngine.train(training_ds , idataset.mTimeVar , lSignalVar, H, lExogenousData);
  File "/home/antoine/dev/python/packages/pyaf/ForecastEngine.py", line 25, in train
    self.mSignalDecomposition.train(iInputDS, iTime, iSignal, iHorizon, iExogenousData);
  File "/home/antoine/dev/python/packages/pyaf/TS/SignalDecomposition.py", line 463, in train
    self.train_multiprocessed(iInputDS, iTime, iSignal, iHorizon);
  File "/home/antoine/dev/python/packages/pyaf/TS/SignalDecomposition.py", line 387, in train_multiprocessed
    for res in pool.imap(run_transform_thread, args):
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 695, in next
    raise value
numpy.linalg.linalg.LinAlgError: SVD did not converge

**Comment by antoinecarme** [comment]
The analysis script does not always fail .... bug or random initialization in numpy SVD algorithm implementation ?

**Comment by antoinecarme** [comment]
Of 2431 test scripts in `tests/artificial` directory, 10 failed with this message:
`

`antoine@z600:~/dev/python/packages/pyaf$ vdir tests/artificial/logs/ | wc -l
2431


antoine@z600:~/dev/python/packages/pyaf$ grep converge tests/artificial/logs/*.log | grep raise
tests/artificial/logs/test_artificial_1024_diff_poly_0__0.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_diff_poly_0__100.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_inv_constant_30__20.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_inv_linear_7_12_100.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_log_linear_30_12_20.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_log_linear_5_12_100.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024__poly_7_12_100.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_sqr_poly_5_12_20.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_sqrt_constant_7_12_100.log:    raise LinAlgError("SVD did not converge")
tests/artificial/logs/test_artificial_1024_sqrt_linear_30_12_20.log:    raise LinAlgError("SVD did not converge")

**Comment by antoinecarme** [comment]
There is a similar bug in numpy : still open (since 2012)

https://github.com/numpy/numpy/issues/1588

**Comment by antoinecarme** [comment]
possible fix : Depends on the lapack version installed.

**Comment by antoinecarme** [comment]
A possible fix is to simply ignore this situation (for the moment ?).

PyAF is running a competition between a large set of possible models. This issue happens when one model fails. We should give  a chance to th remaining models to give a good prediction.

In case a scikit-learn training/fit fails, we will replace the model with a default (constant = mean(signal) or mean(residue)). A very polite way of discarding it ;)
