### ISSUE TITLE
Remove logging error messages from benchmarks logs

### ISSUE THREAD

**Issue by antoinecarme** [antoinecarme/pyaf#54]
The benchmraks logs show some error messages probably due to logging while multiprocessing.
Need to find a solution.

For example : 

https://github.com/antoinecarme/PyAF_Benchmarks/blob/master/NN3_PART_1/PyAF_NN3_PART_1_NN3-010_18.log

```

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "benches/run_benchmark_NN3.py", line 14, in <module>
    tester1.run_multiprocessed();
  File "/home/antoine/dev/python/packages/pyaf/Bench/GenericBenchmark.py", line 335, in run_multiprocessed
    pool = mp.Pool(processes=nbprocesses, maxtasksperchild=None)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
```

**Comment by antoinecarme** [comment]
Fixed
